var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__012d94b8._.js")
R.c("server/chunks/ssr/node_modules_8c3db903._.js")
R.c("server/chunks/ssr/node_modules_next_dist_7da8c22c._.js")
R.c("server/chunks/ssr/src_app_ca777385._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6001fd35._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__be0d5024._.js")
R.c("server/chunks/ssr/_a2985d5b._.js")
R.c("server/chunks/ssr/_f443938a._.js")
R.m(396669)
R.m(68509)
module.exports=R.m(68509).exports
